channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - ome::zeroc-ice36-python==3.6.5
  - conda-forge::ipywidgets==8.0.4
  - dask
  - pip
  - pip:
    - omero-py==5.13.1
    - ome-zarr==0.7.1
    - dask-image==2023.3.0
    - matplotlib==3.7.1
