name: imaging_course_minio_day5_2023
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
  - joshmoore
dependencies:
  - pip
  - go-mc
  - pip:
    - napari[all]
    - napari-ome-zarr==0.5.2

