# Builds the repository using mamba

---
name: build

on: 
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        envs: [Day_4/environment_cellpose.yml, Day_4/environment.yml]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Conda environment for ${{ matrix.envs }} with Micromamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ${{ matrix.envs }}
